[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://hyzyncv2.netlify.app/bionic/*"
  to = "https://hyzyncv2.netlify.app"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://hyzyncv2.netlify.app"
  status = 200
