[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/bionic/*"
  to = "/build/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/build/index.html"
  status = 200
